print("Family members")
print("mother:rani")
print("sister: sangeetha,viji,moni,priya,sathana")
print("brther:praveen,bala")
print("friends")
print("saravana")
print("kirthu")
print("suresh")
print("vishunu")
print("priya")
print("rajesh")
print("sathya")
