a =int(input("enter a number :"))
b =int(input("enter a number :"))
c=float(input("enter a number :"))
length =10
breadth =5
area =(length + breadth)
SI =(a+b+c)/100
cost =float(input("enter cost"))
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print((a*2),(b*2))
print((a*3),(b*3))
print(a+b+c/3)
print("swapping","a =",b,"b =",a)
print(type(a),type(b),type(c))
print(a+c)
print(a>b)
print(a==b)
print((a+b+c),(a+b+c/3))
print(c*60)
print(SI)
print(area)
print("positive")
print("totalcost=",cost*int(input("enter quantity: ")))
print((a+b),(a-b),(a*b),(a/b))
                                  
